### Get genre
GET  http://localhost:3000/api/genres?genre=Pop

### Get genres
GET  http://localhost:3000/api/genres

### Create a new genre
POST http://localhost:3000/api/genres/
content-type: application/json

{
  "genre": {
    "name": "Rock"
  }
}

### Delete a Genre
DELETE http://localhost:3000/api/genres/64dc8ab23ced77e3086743a8
