### Create a new group
POST http://localhost:3000/api/groups/
content-type: application/json

{
  "group": {
    "name": "Alice Cooper",
    "fundationDate": 1964,
    "members": ["Vincent Damon Furnie"],
    "genres": ["Rock"]
  }
}
