### Get group
GET  http://localhost:3000/api/groups?group=Alice%20Cooper

### Get groups
GET  http://localhost:3000/api/groups

### Create a new group
POST http://localhost:3000/api/groups
content-type: application/json

{
  "group": {
    "name": "Hombres G",
    "fundationDate": 1982,
    "members": ["David Summers", "Rafa Gutierrez", "Javier Molina", "Daniel Mezquita"],
    "genres": ["Rock"]
  }
}

### Delete a group
DELETE http://localhost:3000/api/groups/64dc7ae9bd2704ac7e548a6e
