### Get users
GET http://localhost:3000/api/users/

### Get user
GET http://localhost:3000/api/users/

### Get users with one genre
GET http://localhost:3000/api/users/genre/Rock

### Get users with one group
GET http://localhost:3000/api/users/group/Alice%20Cooper

### Create a new user
POST http://localhost:3000/api/users/
content-type: application/json

{
  "user": {
    "name": "Usuario",
    "email": "usuario@gmail.com"
  }
}

### Update an user
PUT http://localhost:3000/api/users/64e703efc1c2c96198836ab8
content-type: application/json

{
  "payload": {
    "name": "Usuario"
  }
}

### Add genre to user
PUT http://localhost:3000/api/users/64e703efc1c2c96198836ab8/genre/Pop

### Add group to user
PUT http://localhost:3000/api/users/64e703efc1c2c96198836ab8/group/Alice%20Cooper

### Delete an user
DELETE http://localhost:3000/api/users/64d227af41b5e72b44c36e23