### Get users
GET http://localhost:3000/api/users/

### Get user
GET http://localhost:3000/api/users/

### Get users with one genre
GET http://localhost:3000/api/users/genre/Pop

### Get users with one group
GET http://localhost:3000/api/users/group/Estopa

### Create a new user
POST http://localhost:3000/api/users/
content-type: application/json

{
  "user": {
    "name": "Erika Perez",
    "email": "erika@gmail.com"
  }
}

### Update an user
PUT http://localhost:3000/api/users/:userId
content-type: application/json

{
  "user": {
    "id": "0123456789"
  }
}

### Add genre to user
PUT http://localhost:3000/api/users/64d343a2c437a682aee812f5/genre/Rock

### Add group to user
PUT http://localhost:3000/api/users/64d343a2c437a682aee812f5/group/Alice%20Cooper

### Delete an user
DELETE http://localhost:3000/api/users/32
