### Get users
GET http://localhost:3000/api/users/

### Get user
GET http://localhost:3000/api/users/

### Get users with one genre
GET http://localhost:3000/api/users/genre/Rock

### Get users with one group
GET http://localhost:3000/api/users/group/Alice%20Cooper

### Create a new user
POST http://localhost:3000/api/users/
content-type: application/json

{
  "user": {
    "name": "Erika Perez",
    "email": "erika@gmail.com"
  }
}

### Update an user
PUT http://localhost:3000/api/users/:userId
content-type: application/json

{
  "user": {
    "id": "0123456789"
  }
}

### Add genre to user
PUT http://localhost:3000/api/users/64d50bf71020c2401ec7d34c/genre/Rock

### Add group to user
PUT http://localhost:3000/api/users/64dc7ae9bd2704ac7e548a6e/group/Hombres%20G

### Delete an user
DELETE http://localhost:3000/api/users/64d227af41b5e72b44c36e23